[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["python"]

[deploy]
startCommand = "python -m src.tg_service.tg_bot"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckTimeout = 300

[service]
internalPort = 8080
